
export const categoriesToColors = {
    Fihavanana: '#c7d2fe',
    Firaisan_kina: '#bbf7d0',
    Fahafatesana: '#bfdbfe',
    Fisaorana: '#e2e8f0',
    Hafaliana: '#e7e5e4',
    Zanaka: '#fed7aa',
    Ray_aman_dreny: '#fde68a',
    Fahamorana: '#d9f99d',
    Fanambadiana: '#fef08a',
    Zanahary: '#a7f3d0',
    Razana: '#99f6e4',
    Fifanajana: '#fbcfe8',
    Fandrosoana: '#a5f3fc',
    Namana: '#fecaca',
    Fitafiana: '#bae6fd',
    Tsiny: '#e9d5ff',
    Lahatra: '#f5d0fe',
    Anjara: '#fecdd3',
    Fahadiovana: '#e5e7eb',
    Fahasambarana: '#e5e5e5',
    Firarian_tsoa: '#fecaca',
    Tsondrano: '#d9f99d',
    Hanatra: '#d9f99d',
    Fianarana: '#fef08a',
    Fahendrena: '#fed7aa',
};

export const regions = [
    "Analamanga",
    "Diana",
    "Sava",
    "Itasy",
    "Vakinankaratra",
    "Bongolava",
    "Sofia",
    "Boeny",
    "Betsiboka",
    "Melaky",
    "Alaotra Mangoro",
    "Antsinanana",
    "Analanjirofo",
    "Ambatosoa",
    "Amoron'i Mania",
    "Vatovavy",
    "Fitovinany",
    "Haute Matsiatra",
    "Atsimo Atsinanana",
    "Ihorombe",
    "Menabe",
    "Atsimo Andrefana",
    "Androy",
    "Anosy",
]

export const categorys = [
    "Fihavanana",
    "Firaisan_kina",
    "Fitiavana",
    "Fahafatesana",
    "Fisaorana",
    "Hafaliana",
    "Zanaka",
    "Ray_aman_dreny",
    "Fahamorana",
    "Fanambadiana",
    "Zanahary",
    "Razana",
    "Fifanajana",
    "Fandrosoana",
    "Namana",
    "Fitafiana",
    "Tsiny",
    "Lahatra",
    "Anjara",
    "Fahadiovana",
    "Fahasambarana",
    "Firarian_tsoa",
    "Tsondrano",
    "Hanatra",
    "Fianarana",
    "Fahendrena",
]